config main 'main'
	option enabled '1'
	option rpc_debug_level '4'
	option timeout '1'
	option baudrate '2400'
	option scan_type 'secondary'

config group '0'
	option enabled '1'
	option name 'Default group'
	option period '60'
	option data_type '4'
	option prefix '['
	option midfix ','
	option postfix ']'
